version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=logstash
      - node.name=ilos

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"

  logstash:
    build: ./logstash
    ports:
      - "25826:25826/udp"
    environment:
      - discovery.type=single-node
      - cluster.name=logstash
      - node.name=ilos
      - var.elasticsearch.hosts=elasticsearch
      - var.elasticsearch.username=elastic
      - var.elasticsearch.password=changeme
