# -*- mode: ruby -*-
# vi: set ft=ruby :
# This vagrant file setups the machines we want to monitor

Vagrant.configure("2") do |config|
  
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"

    ubuntu.vm.network "private_network", ip: "192.168.33.10"
    ubuntu.vm.hostname = "ubuntu-1.local"
    ubuntu.ssh.forward_agent = true

    ubuntu.vm.provision "file", source: "./keys/authorized_keys", destination: "/home/vagrant/.ssh/authorized_keys"
    ubuntu.vm.provision "shell", inline: "sudo apt-get update; sudo apt-get -y install python"

    ubuntu.vm.provider "virtualbox" do |vb|
       vb.memory = 512
       vb.cpus = 2
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "private_network", ip: "192.168.33.11"
    centos.vm.hostname = "centos-1.local"
    centos.ssh.forward_agent = true

    centos.vm.provision "file", source: "./keys/authorized_keys", destination: "/home/vagrant/.ssh/authorized_keys"
    centos.vm.provision "shell", inline: "yum -y install python"

    centos.vm.provider "virtualbox" do |vb|
       vb.memory = 512
       vb.cpus = 2
    end
  end

  config.vm.define "ubuntu2" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"

    ubuntu.vm.network "private_network", ip: "192.168.33.12"
    ubuntu.vm.hostname = "ubuntu-2.local"
    ubuntu.ssh.forward_agent = true

    ubuntu.vm.provision "file", source: "./keys/authorized_keys", destination: "/home/vagrant/.ssh/authorized_keys"
    ubuntu.vm.provision "shell", inline: "sudo apt-get update; sudo apt-get -y install python"

    ubuntu.vm.provider "virtualbox" do |vb|
       vb.memory = 512
       vb.cpus = 2
    end
  end

  config.vm.define "centos2" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "private_network", ip: "192.168.33.13"
    centos.vm.hostname = "centos-2.local"
    centos.ssh.forward_agent = true

    centos.vm.provision "file", source: "./keys/authorized_keys", destination: "/home/vagrant/.ssh/authorized_keys"
    centos.vm.provision "shell", inline: "yum -y install python"

    centos.vm.provider "virtualbox" do |vb|
       vb.memory = 512
       vb.cpus = 2
    end
  end

end
