# -*- mode: ruby -*-
# vi: set ft=ruby :
# This vagrant file setups the machines we want to monitor

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"

    ubuntu.vm.network "private_network", ip: "192.168.33.10"
    ubuntu.vm.hostname = "ubuntu.local"
    ubuntu.ssh.forward_agent = true

    ubuntu.vm.provision "file", source: "./keys/authorized_keys", destination: "/home/vagrant/.ssh/authorized_keys"
    ubuntu.vm.provision "shell", inline: "sudo apt-get update; sudo apt-get -y install python"



    ubuntu.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "private_network", ip: "192.168.33.11"
    centos.vm.hostname = "centos.local"
    centos.ssh.forward_agent = true
    
    centos.vm.provision "file", source: "./keys/authorized_keys", destination: "/home/vagrant/.ssh/authorized_keys"
    centos.vm.provision "shell", inline: "yum install python"


    centos.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end
  end

end
